version: '20230408'

services:
  attendance_web:
    image: khanhnt1011/timekeeperfaceweb:20230408
    build: '.'
    command: ["npm", "start"]
    environment:
      NODE_ENV: development
    env_file:
      - ./.env.development
    ports:
      - 3000:3000